### ISSUE TITLE
Polytheism repeat does not work properly

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1448] opened 2024-01-05 04:03 UTC
When testing in studio, if you have a card in hand without a symbol previously melded, you should meld it.  However, it skips to the end (the tuck) instead.

**Comment by micahstairs** [comment] 2024-01-07 02:10
Duplicate of https://boardgamearena.com/bug?id=109520. A fix is pending.

**Closed as not planned by micahstairs** 2024-01-07 02:10 UTC
Labels: bug, backend
