### ISSUE TITLE
The "if you don't" on heirloom doesn't appear to be applied

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1399] opened 2023-10-25 04:25 UTC
I was in a game where I shared heirloom and they had a 2 in their safe and here is the sequence:

![image](https://github.com/micahstairs/bga-innovation/assets/11416698/96cb60d9-ca2c-4356-9268-190e66972ee0)

According to the card, they don't do the second transfer if they did the first step of the interaction.

**Comment by ultimatefiend** [comment] 2023-10-25 04:28
This is a comment in the code:

     // "If you don't" happens whenever you either are unable to transfer a secret or you draw a
      // card of a different value than one higher of the transferred secret.
      if (self::getNumChosen() === 0 || $card['age'] != $valueToDraw) {
 
So, if you draw the card (which you always do) you do the second part of it as well?  Both of us were confused by this...I would say if they didn't do both parts of the first interaction (the "and" conditon), then the second part doesn't happen.

**Comment by ultimatefiend** [comment] 2023-10-25 04:35
I think (generally) the "if you don't" needs to be more specific.  "If you don't do both" would be clearer.

**Comment by micahstairs** [comment] 2023-10-25 11:11
That sounds like feedback for that form Chris and Carl set up

**Comment by micahstairs** [comment] 2023-10-28 00:54
Marking as not a bug though.

**Closed as not planned by micahstairs** 2023-10-28 00:54 UTC
