### ISSUE TITLE
Special Achievements are not checked properly when two people are eligible at the same time

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#757] opened 2022-11-18 02:19 UTC
This came up with Qtrie's issue:

https://boardgamearena.com/bug?id=75544

**Comment by micahstairs** [comment] 2022-11-18 11:55
I believe the root cause is in `getActivePlayerIdsInTurnOrderStartingWithCurrentPlayer()`, likely with how we determine who the "current player" is.

Not going to lie, this will be annoying to fix (and test that it's working well), but it's worth doing.

**Comment by micahstairs** [comment] 2022-11-20 02:40
I think this is best fixed by reverting the special achievement changes (https://github.com/micahstairs/bga-innovation/issues/764).

**Comment by micahstairs** [comment] 2022-11-23 02:04
This is no longer worth doing now that we've changed the special achievement check back.

**Closed by micahstairs** 2022-11-23 02:04 UTC
Labels: bug, production, low priority, backend
